version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "S3 bucket URL"
    BUILD_FOLDER: "dist"

  phases:
    install:
      runtime-versions:
        nodejs: 20
      commands:
        - echo Installing NPM dependencies
        - npm cache clean --force
        - npm install -g @angular/cli@latest
        - npm install

    build:
      commands:
        - echo Build started
        - ng build
  artifacts:
    files:
      - "**/*"
    base-directory: "./dist*"
    discard-paths: yes
